# Exercise 3: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [2]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.12863669, 0.3232079 , 0.48752829, 0.84223266, 0.12880116,
        0.2469955 , 0.46191345, 0.91098956, 0.19867012, 0.16684741],
       [0.81610802, 0.1893226 , 0.00887995, 0.18363345, 0.18664089,
        0.86873497, 0.99366715, 0.26596984, 0.16779417, 0.59448141],
       [0.09113021, 0.34187344, 0.58709893, 0.77446582, 0.46392432,
        0.22215929, 0.60255931, 0.69937524, 0.1374323 , 0.23790527],
       [0.79252087, 0.011967  , 0.03415564, 0.63626093, 0.66793921,
        0.76015972, 0.54760799, 0.25888551, 0.18844869, 0.43783146],
       [0.55145215, 0.59737991, 0.10687194, 0.24575509, 0.20155871,
        0.53563074, 0.8898547 , 0.44246326, 0.02469712, 0.67442879],
       [0.12426804, 0.00906422, 0.26864905, 0.71206595, 0.40264541,
        0.96604794, 0.55768393, 0.65935949, 0.01931853, 0.31281369],
       [0.17277765, 0.20531059, 0.93630769, 0.1707634 , 0.12048862,
        0.95104293, 0.59881337, 0.10104666, 0.3619316 , 0.20335203],
       [0.55570194, 0.94492276, 0.3880344

In [3]:
#3.3: return only the odd rows of A
A[0:10:2,:] # start:stop:stepsize , all

array([[0.12863669, 0.3232079 , 0.48752829, 0.84223266, 0.12880116,
        0.2469955 , 0.46191345, 0.91098956, 0.19867012, 0.16684741],
       [0.09113021, 0.34187344, 0.58709893, 0.77446582, 0.46392432,
        0.22215929, 0.60255931, 0.69937524, 0.1374323 , 0.23790527],
       [0.55145215, 0.59737991, 0.10687194, 0.24575509, 0.20155871,
        0.53563074, 0.8898547 , 0.44246326, 0.02469712, 0.67442879],
       [0.17277765, 0.20531059, 0.93630769, 0.1707634 , 0.12048862,
        0.95104293, 0.59881337, 0.10104666, 0.3619316 , 0.20335203],
       [0.12992484, 0.99828723, 0.33545074, 0.51480853, 0.53184242,
        0.69543754, 0.07241584, 0.77210694, 0.88226641, 0.03913563]])

In [ ]:
#3.4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

In [4]:
#3.5: compute the matrix inverse of A
A_inv=np.linalg.inv(A)
np.isclose(A.dot(A_inv),np.identity(10))#test for identity AA^-1

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask=A>0.5
A[mask]/=2
A


In [ ]:
#in one line
A[A>0.5]/=2