# Exercise 3: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [2]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.26537374, 0.52297521, 0.32182756, 0.15584648, 0.67373421,
        0.38351671, 0.69492692, 0.07001381, 0.2462241 , 0.14587183],
       [0.82277074, 0.55869428, 0.47887681, 0.59397202, 0.92684875,
        0.90286414, 0.91129466, 0.29491612, 0.53683909, 0.48109519],
       [0.65232476, 0.8641861 , 0.48049122, 0.62457056, 0.27303746,
        0.74576315, 0.70950637, 0.23673019, 0.51331386, 0.55412068],
       [0.48675659, 0.07487404, 0.52091538, 0.10362879, 0.25184563,
        0.95796967, 0.14514431, 0.18404714, 0.69067023, 0.16752874],
       [0.93472824, 0.31632681, 0.28220144, 0.45321818, 0.72601104,
        0.43960527, 0.54499437, 0.84157097, 0.03338135, 0.1544866 ],
       [0.35331947, 0.11259826, 0.45552322, 0.63031331, 0.92174528,
        0.4258452 , 0.8682303 , 0.04181519, 0.91178721, 0.72124365],
       [0.7047278 , 0.79210897, 0.05959963, 0.198937  , 0.47810523,
        0.31716411, 0.02393146, 0.34928643, 0.57321331, 0.79243553],
       [0.12111198, 0.30857277, 0.3597804

In [3]:
#3.3: return only the odd rows of A
A[0:10:2,:] # start:stop:stepsize , all

array([[0.26537374, 0.52297521, 0.32182756, 0.15584648, 0.67373421,
        0.38351671, 0.69492692, 0.07001381, 0.2462241 , 0.14587183],
       [0.65232476, 0.8641861 , 0.48049122, 0.62457056, 0.27303746,
        0.74576315, 0.70950637, 0.23673019, 0.51331386, 0.55412068],
       [0.93472824, 0.31632681, 0.28220144, 0.45321818, 0.72601104,
        0.43960527, 0.54499437, 0.84157097, 0.03338135, 0.1544866 ],
       [0.7047278 , 0.79210897, 0.05959963, 0.198937  , 0.47810523,
        0.31716411, 0.02393146, 0.34928643, 0.57321331, 0.79243553],
       [0.03278664, 0.84349974, 0.00565218, 0.47283111, 0.43133677,
        0.9423745 , 0.95331256, 0.11165512, 0.62969716, 0.15913658]])

In [4]:
#3.4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

array([[1.64252049, 2.58421474, 2.06384781, 1.19744709, 1.70107789,
        2.11780728, 1.39302606, 2.05037862, 2.02592108, 1.39521771],
       [2.58421474, 4.68251127, 3.80552699, 2.48959069, 3.25702841,
        3.8249512 , 2.71234644, 3.54217556, 3.34869303, 2.66398011],
       [2.06384781, 3.80552699, 3.55399888, 2.07434107, 2.51648485,
        3.00318847, 2.49720762, 2.86821681, 2.9831464 , 2.47567982],
       [1.19744709, 2.48959069, 2.07434107, 2.06579342, 1.55953856,
        2.0073912 , 1.47465936, 1.79973011, 1.76294576, 1.74061986],
       [1.70107789, 3.25702841, 2.51648485, 1.55953856, 3.00940972,
        2.28672558, 1.95135908, 2.26201702, 1.89990724, 1.52530186],
       [2.11780728, 3.8249512 , 3.00318847, 2.0073912 , 2.28672558,
        3.88038847, 2.19605102, 3.32516838, 2.72734529, 2.32957529],
       [1.39302606, 2.71234644, 2.49720762, 1.47465936, 1.95135908,
        2.19605102, 2.57548493, 2.09473622, 1.83963163, 1.52431219],
       [2.05037862, 3.54217556, 2.8682168

In [5]:
#3.5: compute the matrix inverse of A
A_inv=np.linalg.inv(A)
np.isclose(A.dot(A_inv),np.identity(10))#test for identity AA^-1

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [6]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask=A>0.5
A[mask]/=2
A


array([[0.26537374, 0.26148761, 0.32182756, 0.15584648, 0.3368671 ,
        0.38351671, 0.34746346, 0.07001381, 0.2462241 , 0.14587183],
       [0.41138537, 0.27934714, 0.47887681, 0.29698601, 0.46342438,
        0.45143207, 0.45564733, 0.29491612, 0.26841955, 0.48109519],
       [0.32616238, 0.43209305, 0.48049122, 0.31228528, 0.27303746,
        0.37288157, 0.35475319, 0.23673019, 0.25665693, 0.27706034],
       [0.48675659, 0.07487404, 0.26045769, 0.10362879, 0.25184563,
        0.47898483, 0.14514431, 0.18404714, 0.34533511, 0.16752874],
       [0.46736412, 0.31632681, 0.28220144, 0.45321818, 0.36300552,
        0.43960527, 0.27249718, 0.42078549, 0.03338135, 0.1544866 ],
       [0.35331947, 0.11259826, 0.45552322, 0.31515666, 0.46087264,
        0.4258452 , 0.43411515, 0.04181519, 0.4558936 , 0.36062183],
       [0.3523639 , 0.39605448, 0.05959963, 0.198937  , 0.47810523,
        0.31716411, 0.02393146, 0.34928643, 0.28660666, 0.39621777],
       [0.12111198, 0.30857277, 0.3597804

In [7]:
#in one line
A[A>0.5]/=2